name: Dispatch Trigger

on:
  repository_dispatch:
    types: [trigger-asv]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: airspeed-velocity
          repo: asv
          github_token: ${{ secrets.ASV_TOK }}
          workflow_file_name: triggered.yml
          ref: master
          wait_workflow: true
          client_payload: '{"pr_number": "${{ github.event.pull_request.number }}"}'
