name: Trigger Dispatch Event

on:
  pull_request:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger repository_dispatch event
        run: |
          curl -X POST \
               -H "Authorization: token ${{ secrets.ASV_TOK }}" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               "https://api.github.com/repos/airspeed-velocity/asv_runner/dispatches" \
               --data '{"event_type": "trigger-asv", "client_payload": {"pr_number": "${{ github.event.pull_request.number }}"} }'
