name: Trigger asv
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  buildmamba:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 0
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: airspeed-velocity
          repo: asv
          github_token: ${{ secrets.ASV_TOK }}
          workflow_file_name: triggered.yml
          ref: master
          wait_workflow: true
          client_payload: '{"pr_number": "${{ github.event.pull_request.number }}"}'
